server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: products
          uri:
            http://localhost:8081/
        - id: cart
          uri:
            http://localhost:8082/
        - id: news
          uri:
            http://localhost:8083/