server:
  port: 8081
spring:
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    password: products
    username: products
    url: jdbc:postgresql://localhost:5432/products